In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
df = pd.read_csv("/content/Indian Stock Market Data.csv")

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
df

,Date,Open,High,Low,Close,Adj Close,Volume,Company
0,2017-04-03,340.600006,343.899994,338.750000,342.100006,333.047882,2441776.0,ADANIPORTS
1,2017-04-05,343.850006,359.250000,343.049988,358.149994,348.673157,5947873.0,ADANIPORTS
2,2017-04-06,355.750000,358.600006,351.100006,356.649994,347.212799,3524928.0,ADANIPORTS
3,2017-04-07,352.250000,353.350006,345.549988,347.149994,337.964233,4918075.0,ADANIPORTS
4,2017-04-10,348.049988,353.850006,346.049988,352.149994,342.831909,2222773.0,ADANIPORTS
...,...,...,...,...,...,...,...,...
59066,2022-01-13,663.200012,666.000000,648.000000,649.750000,648.693848,30752967.0,WIPRO
59067,2022-01-14,649.250000,649.250000,636.500000,639.799988,638.760010,13257274.0,WIPRO
59068,2022-01-17,639.500000,651.650024,633.049988,646.650024,645.598938,10228938.0,WIPRO
59069,2022-01-18,648.900024,650.000000,631.150024,633.299988,632.270569,7164990.0,WIPRO
59070,2022-01-19,631.000000,631.650024,619.000000,621.150024,620.140381,8691383.0,WIPRO

In [ ]:
df.isnull().sum()

Date         0
Open         1
High         1
Low          1
Close        1
Adj Close    1
Volume       1
Company      0
dtype: int64

In [ ]:
df.fillna(df.mean(numeric_only=True), inplace=True)

In [ ]:
df["Company"] = df["Company"].map({'ADANIPORTS': 1, 'ASIANPAINT': 2, 'AXISBANK': 3, 'BAJAJ-AUTO': 4, 'BAJAJFINSV': 5, 'BAJFINANCE': 6, 'BHARTIARTL': 7, 'BPCL': 8, 'BRITANNIA': 9, 'CIPLA': 10, 'COALINDIA': 11, 'DIVISLAB': 12, 'DRREDDY': 13, 'EICHERMOT': 14, 'GRASIM': 15, 'HCLTECH': 16, 'HDFC': 17, 'HDFCBANK': 18, 'HDFCLIFE': 19, 'HEROMOTOCO': 20, 'HINDALCO': 21, 'HINDUNILVR': 22, 'ICICIBANK': 23, 'INDUSINDBK': 24, 'INFY': 25, 'IOC': 26, 'ITC': 27, 'JSWSTEEL': 28, 'KOTAKBANK': 29, 'LT': 30, 'M&M': 31, 'MARUTI': 32, 'NESTLEIND': 33, 'NTPC': 34, 'ONGC': 35, 'POWERGRID': 36, 'RELIANCE': 37, 'SBILIFE': 38, 'SBIN': 39, 'SHREECEM': 40, 'SUNPHARMA': 41, 'TATACONSUM': 42, 'TATAMOTORS': 43, 'TATASTEEL': 44, 'TCS': 45, 'TECHM': 46, 'TITAN': 47, 'ULTRACEMCO': 48, 'UPL': 49, 'WIPRO': 50})

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59071 entries, 0 to 59070
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       59071 non-null  datetime64[ns]
 1   Open       59071 non-null  float64
 2   High       59071 non-null  float64
 3   Low        59071 non-null  float64
 4   Close      59071 non-null  float64
 5   Adj Close  59071 non-null  float64
 6   Volume     59071 non-null  float64
 7   Company    59071 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(1)
memory usage: 3.6 MB

In [ ]:
df.shape

(59071, 8)

In [ ]:
df.describe()

,Date,Open,High,Low,Close,Adj Close,Volume,Company
count,59071,59071.000000,59071.000000,59071.000000,59071.000000,59071.000000,5.907100e+04,59071.000000
mean,2019-09-01 00:30:59.023886336,2073.959784,2099.919425,2045.670514,2072.179082,2026.102712,7.078442e+06,25.490765
min,2017-04-03 00:00:00,59.400002,63.000000,50.000000,60.000000,52.137356,8.700000e+02,1.000000
25%,2018-06-18 00:00:00,374.000000,379.850006,367.500000,373.350006,356.452347,1.076600e+06,13.000000
50%,2019-09-04 00:00:00,772.000000,781.799988,762.000000,771.349976,758.110840,3.202080e+06,26.000000
75%,2020-11-11 00:00:00,2104.949951,2130.000000,2074.949951,2102.419922,2039.961182,7.991542e+06,38.000000
max,2022-01-20 00:00:00,31682.400391,32048.000000,31120.000000,31748.750000,31680.917969,3.905778e+08,50.000000
std,NaN,3722.234409,3769.542815,3670.927920,3719.448988,3682.505559,1.253730e+07,14.449879

In [ ]:
X = df.drop(['Close', 'Date'], axis=1)
y = df['Close']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [ ]:
y_pred = rf_model.predict(X_test)

In [ ]:
accuracy = r2_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9999717761578077

In [ ]:
rf_model.score(X_test, y_test)

0.9999717761578077

In [ ]:
rf_model.score(X_train, y_train)

0.9999955510970683

In [ ]:
Open = float(input("Enter Open price: "))
High = float(input("Enter High price: "))
Low = float(input("Enter Low price: "))
Adj_Close = float(input("Enter Adjusted Close price: "))
Volume = float(input("Enter Volume: "))
Company = int(input("Enter Company ID (1-50 based on mapping): "))

new_data_for_prediction = pd.DataFrame({
    'Open': [Open],
    'High': [High],
    'Low': [Low],
    'Adj Close': [Adj_Close],
    'Volume': [Volume],
    'Company': [Company]
})

new_data_for_prediction = new_data_for_prediction.reindex(columns=X_train.columns, fill_value=0)

prediction = rf_model.predict(new_data_for_prediction)

print(f"\nPredicted Close Price: {prediction[0]:.2f}")

Enter Open price: 340.600006
Enter High price: 343.899994
Enter Low price: 338.750000
Enter Adjusted Close price: 333.047882
Enter Volume: 2441776.0
Enter Company ID (1-50 based on mapping): 1

Predicted Close Price: 341.75

In [ ]:
import joblib

joblib.dump(rf_model, "Stock_Market_Analysis.joblib")

['Stock_Market_Analysis.joblib']